name: Nasa Project CI
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs: 
  build:
    env:
      CI: true
    strategy:
      matrix:
        node-version: [ 22.x, 20.x ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Use nodejs version ${{matrix.node-version}}
        uses: actions/setup-node@v5
        with:
          node-version: ${{matrix.node-version}}
      - run: npm install
      - name: Install Client Dependencies
        run: npm install --prefix client

      - name: Build Client
        run: npm run build --prefix client
      - run: npm test